package com.mcwstairs.kikoz.init;

import com.mcwstairs.kikoz.MacawsStairs;
import com.mcwstairs.kikoz.util.stone.BalconyItemStone;
import com.mcwstairs.kikoz.util.stone.PlatformItemStone;
import com.mcwstairs.kikoz.util.stone.RailingItemStone;
import com.mcwstairs.kikoz.util.wooden.BalconyItemWooden;
import com.mcwstairs.kikoz.util.wooden.FuelItemBlock;
import com.mcwstairs.kikoz.util.wooden.PlatformItemWooden;
import com.mcwstairs.kikoz.util.wooden.RailingItemWooden;

import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class ItemInit {
	public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS,
			MacawsStairs.MOD_ID);

	public static final RegistryObject<Item> OAK_TERRACE_STAIRS = ITEMS.register("oak_terrace_stairs", () -> new FuelItemBlock(BlockInit.OAK_TERRACE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> SPRUCE_TERRACE_STAIRS = ITEMS.register("spruce_terrace_stairs", () -> new FuelItemBlock(BlockInit.SPRUCE_TERRACE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> BIRCH_TERRACE_STAIRS = ITEMS.register("birch_terrace_stairs", () -> new FuelItemBlock(BlockInit.BIRCH_TERRACE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> JUNGLE_TERRACE_STAIRS = ITEMS.register("jungle_terrace_stairs", () -> new FuelItemBlock(BlockInit.JUNGLE_TERRACE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> ACACIA_TERRACE_STAIRS = ITEMS.register("acacia_terrace_stairs", () -> new FuelItemBlock(BlockInit.ACACIA_TERRACE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> DARK_OAK_TERRACE_STAIRS = ITEMS.register("dark_oak_terrace_stairs", () -> new FuelItemBlock(BlockInit.DARK_OAK_TERRACE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> CRIMSON_TERRACE_STAIRS = ITEMS.register("crimson_terrace_stairs", () -> new FuelItemBlock(BlockInit.CRIMSON_TERRACE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> WARPED_TERRACE_STAIRS = ITEMS.register("warped_terrace_stairs", () -> new FuelItemBlock(BlockInit.WARPED_TERRACE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> MANGROVE_TERRACE_STAIRS = ITEMS.register("mangrove_terrace_stairs", () -> new FuelItemBlock(BlockInit.MANGROVE_TERRACE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> CHERRY_TERRACE_STAIRS = ITEMS.register("cherry_terrace_stairs", () -> new FuelItemBlock(BlockInit.CHERRY_TERRACE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> COBBLESTONE_TERRACE_STAIRS = ITEMS.register("cobblestone_terrace_stairs", () -> new BlockItem(BlockInit.COBBLESTONE_TERRACE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> STONE_BRICK_TERRACE_STAIRS = ITEMS.register("stone_brick_terrace_stairs", () -> new BlockItem(BlockInit.STONE_BRICK_TERRACE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> MOSSY_COBBLESTONE_TERRACE_STAIRS = ITEMS.register("mossy_cobblestone_terrace_stairs", () -> new BlockItem(BlockInit.MOSSY_COBBLESTONE_TERRACE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> MOSSY_STONE_BRICK_TERRACE_STAIRS = ITEMS.register("mossy_stone_brick_terrace_stairs", () -> new BlockItem(BlockInit.MOSSY_STONE_BRICK_TERRACE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> GRANITE_TERRACE_STAIRS = ITEMS.register("granite_terrace_stairs", () -> new BlockItem(BlockInit.GRANITE_TERRACE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> DIORITE_TERRACE_STAIRS = ITEMS.register("diorite_terrace_stairs", () -> new BlockItem(BlockInit.DIORITE_TERRACE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> ANDESITE_TERRACE_STAIRS = ITEMS.register("andesite_terrace_stairs", () -> new BlockItem(BlockInit.ANDESITE_TERRACE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> COBBLED_DEEPSLATE_TERRACE_STAIRS = ITEMS.register("cobbled_deepslate_terrace_stairs", () -> new BlockItem(BlockInit.COBBLED_DEEPSLATE_TERRACE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> DEEPSLATE_BRICK_TERRACE_STAIRS = ITEMS.register("deepslate_brick_terrace_stairs", () -> new BlockItem(BlockInit.DEEPSLATE_BRICK_TERRACE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> BRICK_TERRACE_STAIRS = ITEMS.register("brick_terrace_stairs", () -> new BlockItem(BlockInit.BRICK_TERRACE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> MUD_BRICK_TERRACE_STAIRS = ITEMS.register("mud_brick_terrace_stairs", () -> new BlockItem(BlockInit.MUD_BRICK_TERRACE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> SANDSTONE_TERRACE_STAIRS = ITEMS.register("sandstone_terrace_stairs", () -> new BlockItem(BlockInit.SANDSTONE_TERRACE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> RED_SANDSTONE_TERRACE_STAIRS = ITEMS.register("red_sandstone_terrace_stairs", () -> new BlockItem(BlockInit.RED_SANDSTONE_TERRACE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> PRISMARINE_TERRACE_STAIRS = ITEMS.register("prismarine_terrace_stairs", () -> new BlockItem(BlockInit.PRISMARINE_TERRACE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> NETHER_BRICK_TERRACE_STAIRS = ITEMS.register("nether_brick_terrace_stairs", () -> new BlockItem(BlockInit.NETHER_BRICK_TERRACE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> RED_NETHER_BRICK_TERRACE_STAIRS = ITEMS.register("red_nether_brick_terrace_stairs", () -> new BlockItem(BlockInit.RED_NETHER_BRICK_TERRACE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> BLACKSTONE_TERRACE_STAIRS = ITEMS.register("blackstone_terrace_stairs", () -> new BlockItem(BlockInit.BLACKSTONE_TERRACE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> QUARTZ_TERRACE_STAIRS = ITEMS.register("quartz_terrace_stairs", () -> new BlockItem(BlockInit.QUARTZ_TERRACE_STAIRS.get(), new Item.Properties()));

	public static final RegistryObject<Item> OAK_SKYLINE_STAIRS = ITEMS.register("oak_skyline_stairs", () -> new FuelItemBlock(BlockInit.OAK_SKYLINE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> SPRUCE_SKYLINE_STAIRS = ITEMS.register("spruce_skyline_stairs", () -> new FuelItemBlock(BlockInit.SPRUCE_SKYLINE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> BIRCH_SKYLINE_STAIRS = ITEMS.register("birch_skyline_stairs", () -> new FuelItemBlock(BlockInit.BIRCH_SKYLINE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> JUNGLE_SKYLINE_STAIRS = ITEMS.register("jungle_skyline_stairs", () -> new FuelItemBlock(BlockInit.JUNGLE_SKYLINE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> ACACIA_SKYLINE_STAIRS = ITEMS.register("acacia_skyline_stairs", () -> new FuelItemBlock(BlockInit.ACACIA_SKYLINE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> DARK_OAK_SKYLINE_STAIRS = ITEMS.register("dark_oak_skyline_stairs", () -> new FuelItemBlock(BlockInit.DARK_OAK_SKYLINE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> CRIMSON_SKYLINE_STAIRS = ITEMS.register("crimson_skyline_stairs", () -> new FuelItemBlock(BlockInit.CRIMSON_SKYLINE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> WARPED_SKYLINE_STAIRS = ITEMS.register("warped_skyline_stairs", () -> new FuelItemBlock(BlockInit.WARPED_SKYLINE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> MANGROVE_SKYLINE_STAIRS = ITEMS.register("mangrove_skyline_stairs", () -> new FuelItemBlock(BlockInit.MANGROVE_SKYLINE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> CHERRY_SKYLINE_STAIRS = ITEMS.register("cherry_skyline_stairs", () -> new FuelItemBlock(BlockInit.CHERRY_SKYLINE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> COBBLESTONE_SKYLINE_STAIRS = ITEMS.register("cobblestone_skyline_stairs", () -> new BlockItem(BlockInit.COBBLESTONE_SKYLINE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> STONE_BRICK_SKYLINE_STAIRS = ITEMS.register("stone_brick_skyline_stairs", () -> new BlockItem(BlockInit.STONE_BRICK_SKYLINE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> MOSSY_COBBLESTONE_SKYLINE_STAIRS = ITEMS.register("mossy_cobblestone_skyline_stairs", () -> new BlockItem(BlockInit.MOSSY_COBBLESTONE_SKYLINE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> MOSSY_STONE_BRICK_SKYLINE_STAIRS = ITEMS.register("mossy_stone_brick_skyline_stairs", () -> new BlockItem(BlockInit.MOSSY_STONE_BRICK_SKYLINE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> GRANITE_SKYLINE_STAIRS = ITEMS.register("granite_skyline_stairs", () -> new BlockItem(BlockInit.GRANITE_SKYLINE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> DIORITE_SKYLINE_STAIRS = ITEMS.register("diorite_skyline_stairs", () -> new BlockItem(BlockInit.DIORITE_SKYLINE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> ANDESITE_SKYLINE_STAIRS = ITEMS.register("andesite_skyline_stairs", () -> new BlockItem(BlockInit.ANDESITE_SKYLINE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> COBBLED_DEEPSLATE_SKYLINE_STAIRS = ITEMS.register("cobbled_deepslate_skyline_stairs", () -> new BlockItem(BlockInit.COBBLED_DEEPSLATE_SKYLINE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> DEEPSLATE_BRICK_SKYLINE_STAIRS = ITEMS.register("deepslate_brick_skyline_stairs", () -> new BlockItem(BlockInit.DEEPSLATE_BRICK_SKYLINE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> BRICK_SKYLINE_STAIRS = ITEMS.register("brick_skyline_stairs", () -> new BlockItem(BlockInit.BRICK_SKYLINE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> MUD_BRICK_SKYLINE_STAIRS = ITEMS.register("mud_brick_skyline_stairs", () -> new BlockItem(BlockInit.MUD_BRICK_SKYLINE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> SANDSTONE_SKYLINE_STAIRS = ITEMS.register("sandstone_skyline_stairs", () -> new BlockItem(BlockInit.SANDSTONE_SKYLINE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> RED_SANDSTONE_SKYLINE_STAIRS = ITEMS.register("red_sandstone_skyline_stairs", () -> new BlockItem(BlockInit.RED_SANDSTONE_SKYLINE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> PRISMARINE_SKYLINE_STAIRS = ITEMS.register("prismarine_skyline_stairs", () -> new BlockItem(BlockInit.PRISMARINE_SKYLINE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> NETHER_BRICK_SKYLINE_STAIRS = ITEMS.register("nether_brick_skyline_stairs", () -> new BlockItem(BlockInit.NETHER_BRICK_SKYLINE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> RED_NETHER_BRICK_SKYLINE_STAIRS = ITEMS.register("red_nether_brick_skyline_stairs", () -> new BlockItem(BlockInit.RED_NETHER_BRICK_SKYLINE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> BLACKSTONE_SKYLINE_STAIRS = ITEMS.register("blackstone_skyline_stairs", () -> new BlockItem(BlockInit.BLACKSTONE_SKYLINE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> QUARTZ_SKYLINE_STAIRS = ITEMS.register("quartz_skyline_stairs", () -> new BlockItem(BlockInit.QUARTZ_SKYLINE_STAIRS.get(), new Item.Properties()));

	public static final RegistryObject<Item> OAK_COMPACT_STAIRS = ITEMS.register("oak_compact_stairs", () -> new FuelItemBlock(BlockInit.OAK_COMPACT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> SPRUCE_COMPACT_STAIRS = ITEMS.register("spruce_compact_stairs", () -> new FuelItemBlock(BlockInit.SPRUCE_COMPACT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> BIRCH_COMPACT_STAIRS = ITEMS.register("birch_compact_stairs", () -> new FuelItemBlock(BlockInit.BIRCH_COMPACT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> JUNGLE_COMPACT_STAIRS = ITEMS.register("jungle_compact_stairs", () -> new FuelItemBlock(BlockInit.JUNGLE_COMPACT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> ACACIA_COMPACT_STAIRS = ITEMS.register("acacia_compact_stairs", () -> new FuelItemBlock(BlockInit.ACACIA_COMPACT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> DARK_OAK_COMPACT_STAIRS = ITEMS.register("dark_oak_compact_stairs", () -> new FuelItemBlock(BlockInit.DARK_OAK_COMPACT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> CRIMSON_COMPACT_STAIRS = ITEMS.register("crimson_compact_stairs", () -> new FuelItemBlock(BlockInit.CRIMSON_COMPACT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> WARPED_COMPACT_STAIRS = ITEMS.register("warped_compact_stairs", () -> new FuelItemBlock(BlockInit.WARPED_COMPACT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> MANGROVE_COMPACT_STAIRS = ITEMS.register("mangrove_compact_stairs", () -> new FuelItemBlock(BlockInit.MANGROVE_COMPACT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> CHERRY_COMPACT_STAIRS = ITEMS.register("cherry_compact_stairs", () -> new FuelItemBlock(BlockInit.CHERRY_COMPACT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> COBBLESTONE_COMPACT_STAIRS = ITEMS.register("cobblestone_compact_stairs", () -> new BlockItem(BlockInit.COBBLESTONE_COMPACT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> STONE_BRICK_COMPACT_STAIRS = ITEMS.register("stone_brick_compact_stairs", () -> new BlockItem(BlockInit.STONE_BRICK_COMPACT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> MOSSY_COBBLESTONE_COMPACT_STAIRS = ITEMS.register("mossy_cobblestone_compact_stairs", () -> new BlockItem(BlockInit.MOSSY_COBBLESTONE_COMPACT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> MOSSY_STONE_BRICK_COMPACT_STAIRS = ITEMS.register("mossy_stone_brick_compact_stairs", () -> new BlockItem(BlockInit.MOSSY_STONE_BRICK_COMPACT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> GRANITE_COMPACT_STAIRS = ITEMS.register("granite_compact_stairs", () -> new BlockItem(BlockInit.GRANITE_COMPACT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> DIORITE_COMPACT_STAIRS = ITEMS.register("diorite_compact_stairs", () -> new BlockItem(BlockInit.DIORITE_COMPACT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> ANDESITE_COMPACT_STAIRS = ITEMS.register("andesite_compact_stairs", () -> new BlockItem(BlockInit.ANDESITE_COMPACT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> COBBLED_DEEPSLATE_COMPACT_STAIRS = ITEMS.register("cobbled_deepslate_compact_stairs", () -> new BlockItem(BlockInit.COBBLED_DEEPSLATE_COMPACT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> DEEPSLATE_BRICK_COMPACT_STAIRS = ITEMS.register("deepslate_brick_compact_stairs", () -> new BlockItem(BlockInit.DEEPSLATE_BRICK_COMPACT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> BRICK_COMPACT_STAIRS = ITEMS.register("brick_compact_stairs", () -> new BlockItem(BlockInit.BRICK_COMPACT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> MUD_BRICK_COMPACT_STAIRS = ITEMS.register("mud_brick_compact_stairs", () -> new BlockItem(BlockInit.MUD_BRICK_COMPACT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> SANDSTONE_COMPACT_STAIRS = ITEMS.register("sandstone_compact_stairs", () -> new BlockItem(BlockInit.SANDSTONE_COMPACT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> RED_SANDSTONE_COMPACT_STAIRS = ITEMS.register("red_sandstone_compact_stairs", () -> new BlockItem(BlockInit.RED_SANDSTONE_COMPACT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> PRISMARINE_COMPACT_STAIRS = ITEMS.register("prismarine_compact_stairs", () -> new BlockItem(BlockInit.PRISMARINE_COMPACT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> NETHER_BRICK_COMPACT_STAIRS = ITEMS.register("nether_brick_compact_stairs", () -> new BlockItem(BlockInit.NETHER_BRICK_COMPACT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> RED_NETHER_BRICK_COMPACT_STAIRS = ITEMS.register("red_nether_brick_compact_stairs", () -> new BlockItem(BlockInit.RED_NETHER_BRICK_COMPACT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> BLACKSTONE_COMPACT_STAIRS = ITEMS.register("blackstone_compact_stairs", () -> new BlockItem(BlockInit.BLACKSTONE_COMPACT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> QUARTZ_COMPACT_STAIRS = ITEMS.register("quartz_compact_stairs", () -> new BlockItem(BlockInit.QUARTZ_COMPACT_STAIRS.get(), new Item.Properties()));

	public static final RegistryObject<Item> OAK_BULK_STAIRS = ITEMS.register("oak_bulk_stairs", () -> new FuelItemBlock(BlockInit.OAK_BULK_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> SPRUCE_BULK_STAIRS = ITEMS.register("spruce_bulk_stairs", () -> new FuelItemBlock(BlockInit.SPRUCE_BULK_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> BIRCH_BULK_STAIRS = ITEMS.register("birch_bulk_stairs", () -> new FuelItemBlock(BlockInit.BIRCH_BULK_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> JUNGLE_BULK_STAIRS = ITEMS.register("jungle_bulk_stairs", () -> new FuelItemBlock(BlockInit.JUNGLE_BULK_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> ACACIA_BULK_STAIRS = ITEMS.register("acacia_bulk_stairs", () -> new FuelItemBlock(BlockInit.ACACIA_BULK_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> DARK_OAK_BULK_STAIRS = ITEMS.register("dark_oak_bulk_stairs", () -> new FuelItemBlock(BlockInit.DARK_OAK_BULK_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> CRIMSON_BULK_STAIRS = ITEMS.register("crimson_bulk_stairs", () -> new FuelItemBlock(BlockInit.CRIMSON_BULK_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> WARPED_BULK_STAIRS = ITEMS.register("warped_bulk_stairs", () -> new FuelItemBlock(BlockInit.WARPED_BULK_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> MANGROVE_BULK_STAIRS = ITEMS.register("mangrove_bulk_stairs", () -> new FuelItemBlock(BlockInit.MANGROVE_BULK_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> CHERRY_BULK_STAIRS = ITEMS.register("cherry_bulk_stairs", () -> new FuelItemBlock(BlockInit.CHERRY_BULK_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> COBBLESTONE_BULK_STAIRS = ITEMS.register("cobblestone_bulk_stairs", () -> new BlockItem(BlockInit.COBBLESTONE_BULK_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> STONE_BRICK_BULK_STAIRS = ITEMS.register("stone_brick_bulk_stairs", () -> new BlockItem(BlockInit.STONE_BRICK_BULK_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> MOSSY_COBBLESTONE_BULK_STAIRS = ITEMS.register("mossy_cobblestone_bulk_stairs", () -> new BlockItem(BlockInit.MOSSY_COBBLESTONE_BULK_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> MOSSY_STONE_BRICK_BULK_STAIRS = ITEMS.register("mossy_stone_brick_bulk_stairs", () -> new BlockItem(BlockInit.MOSSY_STONE_BRICK_BULK_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> GRANITE_BULK_STAIRS = ITEMS.register("granite_bulk_stairs", () -> new BlockItem(BlockInit.GRANITE_BULK_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> DIORITE_BULK_STAIRS = ITEMS.register("diorite_bulk_stairs", () -> new BlockItem(BlockInit.DIORITE_BULK_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> ANDESITE_BULK_STAIRS = ITEMS.register("andesite_bulk_stairs", () -> new BlockItem(BlockInit.ANDESITE_BULK_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> COBBLED_DEEPSLATE_BULK_STAIRS = ITEMS.register("cobbled_deepslate_bulk_stairs", () -> new BlockItem(BlockInit.COBBLED_DEEPSLATE_BULK_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> DEEPSLATE_BRICK_BULK_STAIRS = ITEMS.register("deepslate_brick_bulk_stairs", () -> new BlockItem(BlockInit.DEEPSLATE_BRICK_BULK_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> BRICK_BULK_STAIRS = ITEMS.register("brick_bulk_stairs", () -> new BlockItem(BlockInit.BRICK_BULK_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> MUD_BRICK_BULK_STAIRS = ITEMS.register("mud_brick_bulk_stairs", () -> new BlockItem(BlockInit.MUD_BRICK_BULK_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> SANDSTONE_BULK_STAIRS = ITEMS.register("sandstone_bulk_stairs", () -> new BlockItem(BlockInit.SANDSTONE_BULK_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> RED_SANDSTONE_BULK_STAIRS = ITEMS.register("red_sandstone_bulk_stairs", () -> new BlockItem(BlockInit.RED_SANDSTONE_BULK_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> PRISMARINE_BULK_STAIRS = ITEMS.register("prismarine_bulk_stairs", () -> new BlockItem(BlockInit.PRISMARINE_BULK_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> NETHER_BRICK_BULK_STAIRS = ITEMS.register("nether_brick_bulk_stairs", () -> new BlockItem(BlockInit.NETHER_BRICK_BULK_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> RED_NETHER_BRICK_BULK_STAIRS = ITEMS.register("red_nether_brick_bulk_stairs", () -> new BlockItem(BlockInit.RED_NETHER_BRICK_BULK_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> BLACKSTONE_BULK_STAIRS = ITEMS.register("blackstone_bulk_stairs", () -> new BlockItem(BlockInit.BLACKSTONE_BULK_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> QUARTZ_BULK_STAIRS = ITEMS.register("quartz_bulk_stairs", () -> new BlockItem(BlockInit.QUARTZ_BULK_STAIRS.get(), new Item.Properties()));

	public static final RegistryObject<Item> OAK_LOFT_STAIRS = ITEMS.register("oak_loft_stairs", () -> new FuelItemBlock(BlockInit.OAK_LOFT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> SPRUCE_LOFT_STAIRS = ITEMS.register("spruce_loft_stairs", () -> new FuelItemBlock(BlockInit.SPRUCE_LOFT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> BIRCH_LOFT_STAIRS = ITEMS.register("birch_loft_stairs", () -> new FuelItemBlock(BlockInit.BIRCH_LOFT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> JUNGLE_LOFT_STAIRS = ITEMS.register("jungle_loft_stairs", () -> new FuelItemBlock(BlockInit.JUNGLE_LOFT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> ACACIA_LOFT_STAIRS = ITEMS.register("acacia_loft_stairs", () -> new FuelItemBlock(BlockInit.ACACIA_LOFT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> DARK_OAK_LOFT_STAIRS = ITEMS.register("dark_oak_loft_stairs", () -> new FuelItemBlock(BlockInit.DARK_OAK_LOFT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> CRIMSON_LOFT_STAIRS = ITEMS.register("crimson_loft_stairs", () -> new FuelItemBlock(BlockInit.CRIMSON_LOFT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> WARPED_LOFT_STAIRS = ITEMS.register("warped_loft_stairs", () -> new FuelItemBlock(BlockInit.WARPED_LOFT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> MANGROVE_LOFT_STAIRS = ITEMS.register("mangrove_loft_stairs", () -> new FuelItemBlock(BlockInit.MANGROVE_LOFT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> CHERRY_LOFT_STAIRS = ITEMS.register("cherry_loft_stairs", () -> new FuelItemBlock(BlockInit.CHERRY_LOFT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> COBBLESTONE_LOFT_STAIRS = ITEMS.register("cobblestone_loft_stairs", () -> new BlockItem(BlockInit.COBBLESTONE_LOFT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> STONE_BRICK_LOFT_STAIRS = ITEMS.register("stone_brick_loft_stairs", () -> new BlockItem(BlockInit.STONE_BRICK_LOFT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> MOSSY_COBBLESTONE_LOFT_STAIRS = ITEMS.register("mossy_cobblestone_loft_stairs", () -> new BlockItem(BlockInit.MOSSY_COBBLESTONE_LOFT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> MOSSY_STONE_BRICK_LOFT_STAIRS = ITEMS.register("mossy_stone_brick_loft_stairs", () -> new BlockItem(BlockInit.MOSSY_STONE_BRICK_LOFT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> GRANITE_LOFT_STAIRS = ITEMS.register("granite_loft_stairs", () -> new BlockItem(BlockInit.GRANITE_LOFT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> DIORITE_LOFT_STAIRS = ITEMS.register("diorite_loft_stairs", () -> new BlockItem(BlockInit.DIORITE_LOFT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> ANDESITE_LOFT_STAIRS = ITEMS.register("andesite_loft_stairs", () -> new BlockItem(BlockInit.ANDESITE_LOFT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> COBBLED_DEEPSLATE_LOFT_STAIRS = ITEMS.register("cobbled_deepslate_loft_stairs", () -> new BlockItem(BlockInit.COBBLED_DEEPSLATE_LOFT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> DEEPSLATE_BRICK_LOFT_STAIRS = ITEMS.register("deepslate_brick_loft_stairs", () -> new BlockItem(BlockInit.DEEPSLATE_BRICK_LOFT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> BRICK_LOFT_STAIRS = ITEMS.register("brick_loft_stairs", () -> new BlockItem(BlockInit.BRICK_LOFT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> MUD_BRICK_LOFT_STAIRS = ITEMS.register("mud_brick_loft_stairs", () -> new BlockItem(BlockInit.MUD_BRICK_LOFT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> SANDSTONE_LOFT_STAIRS = ITEMS.register("sandstone_loft_stairs", () -> new BlockItem(BlockInit.SANDSTONE_LOFT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> RED_SANDSTONE_LOFT_STAIRS = ITEMS.register("red_sandstone_loft_stairs", () -> new BlockItem(BlockInit.RED_SANDSTONE_LOFT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> PRISMARINE_LOFT_STAIRS = ITEMS.register("prismarine_loft_stairs", () -> new BlockItem(BlockInit.PRISMARINE_LOFT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> NETHER_BRICK_LOFT_STAIRS = ITEMS.register("nether_brick_loft_stairs", () -> new BlockItem(BlockInit.NETHER_BRICK_LOFT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> RED_NETHER_BRICK_LOFT_STAIRS = ITEMS.register("red_nether_brick_loft_stairs", () -> new BlockItem(BlockInit.RED_NETHER_BRICK_LOFT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<Item> BLACKSTONE_LOFT_STAIRS = ITEMS.register("blackstone_loft_stairs", () -> new BlockItem(BlockInit.BLACKSTONE_LOFT_STAIRS.get(), new Item.Properties()));
    public static final RegistryObject<Item> QUARTZ_LOFT_STAIRS = ITEMS.register("quartz_loft_stairs", () -> new BlockItem(BlockInit.QUARTZ_LOFT_STAIRS.get(), new Item.Properties()));
	
    public static final RegistryObject<Item> OAK_RAILING = ITEMS.register("oak_railing", () -> new RailingItemWooden(BlockInit.OAK_RAILING.get(), new Item.Properties()));
	public static final RegistryObject<Item> SPRUCE_RAILING = ITEMS.register("spruce_railing", () -> new RailingItemWooden(BlockInit.SPRUCE_RAILING.get(), new Item.Properties()));
	public static final RegistryObject<Item> BIRCH_RAILING = ITEMS.register("birch_railing", () -> new RailingItemWooden(BlockInit.BIRCH_RAILING.get(), new Item.Properties()));
	public static final RegistryObject<Item> JUNGLE_RAILING = ITEMS.register("jungle_railing", () -> new RailingItemWooden(BlockInit.JUNGLE_RAILING.get(), new Item.Properties()));
	public static final RegistryObject<Item> ACACIA_RAILING = ITEMS.register("acacia_railing", () -> new RailingItemWooden(BlockInit.ACACIA_RAILING.get(), new Item.Properties()));
	public static final RegistryObject<Item> DARK_OAK_RAILING = ITEMS.register("dark_oak_railing", () -> new RailingItemWooden(BlockInit.DARK_OAK_RAILING.get(), new Item.Properties()));
	public static final RegistryObject<Item> CRIMSON_RAILING = ITEMS.register("crimson_railing", () -> new RailingItemWooden(BlockInit.CRIMSON_RAILING.get(), new Item.Properties()));
	public static final RegistryObject<Item> WARPED_RAILING = ITEMS.register("warped_railing", () -> new RailingItemWooden(BlockInit.WARPED_RAILING.get(), new Item.Properties()));
	public static final RegistryObject<Item> MANGROVE_RAILING = ITEMS.register("mangrove_railing", () -> new RailingItemWooden(BlockInit.MANGROVE_RAILING.get(), new Item.Properties()));
	public static final RegistryObject<Item> CHERRY_RAILING = ITEMS.register("cherry_railing", () -> new RailingItemWooden(BlockInit.CHERRY_RAILING.get(), new Item.Properties()));
	public static final RegistryObject<Item> COBBLESTONE_RAILING = ITEMS.register("cobblestone_railing", () -> new RailingItemStone(BlockInit.COBBLESTONE_RAILING.get(), new Item.Properties()));
	public static final RegistryObject<Item> STONE_BRICK_RAILING = ITEMS.register("stone_brick_railing", () -> new RailingItemStone(BlockInit.STONE_BRICK_RAILING.get(), new Item.Properties()));
	public static final RegistryObject<Item> MOSSY_COBBLESTONE_RAILING = ITEMS.register("mossy_cobblestone_railing", () -> new RailingItemStone(BlockInit.MOSSY_COBBLESTONE_RAILING.get(), new Item.Properties()));
	public static final RegistryObject<Item> MOSSY_STONE_BRICK_RAILING = ITEMS.register("mossy_stone_brick_railing", () -> new RailingItemStone(BlockInit.MOSSY_STONE_BRICK_RAILING.get(), new Item.Properties()));
	public static final RegistryObject<Item> GRANITE_RAILING = ITEMS.register("granite_railing", () -> new RailingItemStone(BlockInit.GRANITE_RAILING.get(), new Item.Properties()));
	public static final RegistryObject<Item> DIORITE_RAILING = ITEMS.register("diorite_railing", () -> new RailingItemStone(BlockInit.DIORITE_RAILING.get(), new Item.Properties()));
	public static final RegistryObject<Item> ANDESITE_RAILING = ITEMS.register("andesite_railing", () -> new RailingItemStone(BlockInit.ANDESITE_RAILING.get(), new Item.Properties()));
	public static final RegistryObject<Item> COBBLED_DEEPSLATE_RAILING = ITEMS.register("cobbled_deepslate_railing", () -> new RailingItemStone(BlockInit.COBBLED_DEEPSLATE_RAILING.get(), new Item.Properties()));
	public static final RegistryObject<Item> DEEPSLATE_BRICK_RAILING = ITEMS.register("deepslate_brick_railing", () -> new RailingItemStone(BlockInit.DEEPSLATE_BRICK_RAILING.get(), new Item.Properties()));
	public static final RegistryObject<Item> BRICK_RAILING = ITEMS.register("brick_railing", () -> new RailingItemStone(BlockInit.BRICK_RAILING.get(), new Item.Properties()));
	public static final RegistryObject<Item> MUD_BRICK_RAILING = ITEMS.register("mud_brick_railing", () -> new RailingItemStone(BlockInit.MUD_BRICK_RAILING.get(), new Item.Properties()));
	public static final RegistryObject<Item> SANDSTONE_RAILING = ITEMS.register("sandstone_railing", () -> new RailingItemStone(BlockInit.SANDSTONE_RAILING.get(), new Item.Properties()));
	public static final RegistryObject<Item> RED_SANDSTONE_RAILING = ITEMS.register("red_sandstone_railing", () -> new RailingItemStone(BlockInit.RED_SANDSTONE_RAILING.get(), new Item.Properties()));
	public static final RegistryObject<Item> PRISMARINE_RAILING = ITEMS.register("prismarine_railing", () -> new RailingItemStone(BlockInit.PRISMARINE_RAILING.get(), new Item.Properties()));
	public static final RegistryObject<Item> NETHER_BRICK_RAILING = ITEMS.register("nether_brick_railing", () -> new RailingItemStone(BlockInit.NETHER_BRICK_RAILING.get(), new Item.Properties()));
	public static final RegistryObject<Item> RED_NETHER_BRICK_RAILING = ITEMS.register("red_nether_brick_railing", () -> new RailingItemStone(BlockInit.RED_NETHER_BRICK_RAILING.get(), new Item.Properties()));
	public static final RegistryObject<Item> BLACKSTONE_RAILING = ITEMS.register("blackstone_railing", () -> new RailingItemStone(BlockInit.BLACKSTONE_RAILING.get(), new Item.Properties()));
	public static final RegistryObject<Item> QUARTZ_RAILING = ITEMS.register("quartz_railing", () -> new RailingItemStone(BlockInit.QUARTZ_RAILING.get(), new Item.Properties()));
	
	public static final RegistryObject<Item> OAK_BALCONY = ITEMS.register("oak_balcony", () -> new BalconyItemWooden(BlockInit.OAK_BALCONY.get(), new Item.Properties()));
	public static final RegistryObject<Item> SPRUCE_BALCONY = ITEMS.register("spruce_balcony", () -> new BalconyItemWooden(BlockInit.SPRUCE_BALCONY.get(), new Item.Properties()));
	public static final RegistryObject<Item> BIRCH_BALCONY = ITEMS.register("birch_balcony", () -> new BalconyItemWooden(BlockInit.BIRCH_BALCONY.get(), new Item.Properties()));
	public static final RegistryObject<Item> JUNGLE_BALCONY = ITEMS.register("jungle_balcony", () -> new BalconyItemWooden(BlockInit.JUNGLE_BALCONY.get(), new Item.Properties()));
	public static final RegistryObject<Item> ACACIA_BALCONY = ITEMS.register("acacia_balcony", () -> new BalconyItemWooden(BlockInit.ACACIA_BALCONY.get(), new Item.Properties()));
	public static final RegistryObject<Item> DARK_OAK_BALCONY = ITEMS.register("dark_oak_balcony", () -> new BalconyItemWooden(BlockInit.DARK_OAK_BALCONY.get(), new Item.Properties()));
	public static final RegistryObject<Item> CRIMSON_BALCONY = ITEMS.register("crimson_balcony", () -> new BalconyItemWooden(BlockInit.CRIMSON_BALCONY.get(), new Item.Properties()));
	public static final RegistryObject<Item> WARPED_BALCONY = ITEMS.register("warped_balcony", () -> new BalconyItemWooden(BlockInit.WARPED_BALCONY.get(), new Item.Properties()));
	public static final RegistryObject<Item> MANGROVE_BALCONY = ITEMS.register("mangrove_balcony", () -> new BalconyItemWooden(BlockInit.MANGROVE_BALCONY.get(), new Item.Properties()));
	public static final RegistryObject<Item> CHERRY_BALCONY = ITEMS.register("cherry_balcony", () -> new BalconyItemWooden(BlockInit.CHERRY_BALCONY.get(), new Item.Properties()));
	public static final RegistryObject<Item> COBBLESTONE_BALCONY = ITEMS.register("cobblestone_balcony", () -> new BalconyItemStone(BlockInit.COBBLESTONE_BALCONY.get(), new Item.Properties()));
	public static final RegistryObject<Item> STONE_BRICK_BALCONY = ITEMS.register("stone_brick_balcony", () -> new BalconyItemStone(BlockInit.STONE_BRICK_BALCONY.get(), new Item.Properties()));
	public static final RegistryObject<Item> MOSSY_COBBLESTONE_BALCONY = ITEMS.register("mossy_cobblestone_balcony", () -> new BalconyItemStone(BlockInit.MOSSY_COBBLESTONE_BALCONY.get(), new Item.Properties()));
	public static final RegistryObject<Item> MOSSY_STONE_BRICK_BALCONY = ITEMS.register("mossy_stone_brick_balcony", () -> new BalconyItemStone(BlockInit.MOSSY_STONE_BRICK_BALCONY.get(), new Item.Properties()));
	public static final RegistryObject<Item> GRANITE_BALCONY = ITEMS.register("granite_balcony", () -> new BalconyItemStone(BlockInit.GRANITE_BALCONY.get(), new Item.Properties()));
	public static final RegistryObject<Item> DIORITE_BALCONY = ITEMS.register("diorite_balcony", () -> new BalconyItemStone(BlockInit.DIORITE_BALCONY.get(), new Item.Properties()));
	public static final RegistryObject<Item> ANDESITE_BALCONY = ITEMS.register("andesite_balcony", () -> new BalconyItemStone(BlockInit.ANDESITE_BALCONY.get(), new Item.Properties()));
	public static final RegistryObject<Item> COBBLED_DEEPSLATE_BALCONY = ITEMS.register("cobbled_deepslate_balcony", () -> new BalconyItemStone(BlockInit.COBBLED_DEEPSLATE_BALCONY.get(), new Item.Properties()));
	public static final RegistryObject<Item> DEEPSLATE_BRICK_BALCONY = ITEMS.register("deepslate_brick_balcony", () -> new BalconyItemStone(BlockInit.DEEPSLATE_BRICK_BALCONY.get(), new Item.Properties()));
	public static final RegistryObject<Item> BRICK_BALCONY = ITEMS.register("brick_balcony", () -> new BalconyItemStone(BlockInit.BRICK_BALCONY.get(), new Item.Properties()));
	public static final RegistryObject<Item> MUD_BRICK_BALCONY = ITEMS.register("mud_brick_balcony", () -> new BalconyItemStone(BlockInit.MUD_BRICK_BALCONY.get(), new Item.Properties()));
	public static final RegistryObject<Item> SANDSTONE_BALCONY = ITEMS.register("sandstone_balcony", () -> new BalconyItemStone(BlockInit.SANDSTONE_BALCONY.get(), new Item.Properties()));
	public static final RegistryObject<Item> RED_SANDSTONE_BALCONY = ITEMS.register("red_sandstone_balcony", () -> new BalconyItemStone(BlockInit.RED_SANDSTONE_BALCONY.get(), new Item.Properties()));
	public static final RegistryObject<Item> PRISMARINE_BALCONY = ITEMS.register("prismarine_balcony", () -> new BalconyItemStone(BlockInit.PRISMARINE_BALCONY.get(), new Item.Properties()));
	public static final RegistryObject<Item> NETHER_BRICK_BALCONY = ITEMS.register("nether_brick_balcony", () -> new BalconyItemStone(BlockInit.NETHER_BRICK_BALCONY.get(), new Item.Properties()));
	public static final RegistryObject<Item> RED_NETHER_BRICK_BALCONY = ITEMS.register("red_nether_brick_balcony", () -> new BalconyItemStone(BlockInit.RED_NETHER_BRICK_BALCONY.get(), new Item.Properties()));
	public static final RegistryObject<Item> BLACKSTONE_BALCONY = ITEMS.register("blackstone_balcony", () -> new BalconyItemStone(BlockInit.BLACKSTONE_BALCONY.get(), new Item.Properties()));
	public static final RegistryObject<Item> QUARTZ_BALCONY = ITEMS.register("quartz_balcony", () -> new BalconyItemStone(BlockInit.QUARTZ_BALCONY.get(), new Item.Properties()));
	
	public static final RegistryObject<Item> OAK_PLATFORM = ITEMS.register("oak_platform", () -> new PlatformItemWooden(BlockInit.OAK_PLATFORM.get(), new Item.Properties()));
	public static final RegistryObject<Item> SPRUCE_PLATFORM = ITEMS.register("spruce_platform", () -> new PlatformItemWooden(BlockInit.SPRUCE_PLATFORM.get(), new Item.Properties()));
	public static final RegistryObject<Item> BIRCH_PLATFORM = ITEMS.register("birch_platform", () -> new PlatformItemWooden(BlockInit.BIRCH_PLATFORM.get(), new Item.Properties()));
	public static final RegistryObject<Item> JUNGLE_PLATFORM = ITEMS.register("jungle_platform", () -> new PlatformItemWooden(BlockInit.JUNGLE_PLATFORM.get(), new Item.Properties()));
	public static final RegistryObject<Item> ACACIA_PLATFORM = ITEMS.register("acacia_platform", () -> new PlatformItemWooden(BlockInit.ACACIA_PLATFORM.get(), new Item.Properties()));
	public static final RegistryObject<Item> DARK_OAK_PLATFORM = ITEMS.register("dark_oak_platform", () -> new PlatformItemWooden(BlockInit.DARK_OAK_PLATFORM.get(), new Item.Properties()));
	public static final RegistryObject<Item> CRIMSON_PLATFORM = ITEMS.register("crimson_platform", () -> new PlatformItemWooden(BlockInit.CRIMSON_PLATFORM.get(), new Item.Properties()));
	public static final RegistryObject<Item> WARPED_PLATFORM = ITEMS.register("warped_platform", () -> new PlatformItemWooden(BlockInit.WARPED_PLATFORM.get(), new Item.Properties()));
	public static final RegistryObject<Item> MANGROVE_PLATFORM = ITEMS.register("mangrove_platform", () -> new PlatformItemWooden(BlockInit.MANGROVE_PLATFORM.get(), new Item.Properties()));
	public static final RegistryObject<Item> CHERRY_PLATFORM = ITEMS.register("cherry_platform", () -> new PlatformItemWooden(BlockInit.CHERRY_PLATFORM.get(), new Item.Properties()));
	public static final RegistryObject<Item> COBBLESTONE_PLATFORM = ITEMS.register("cobblestone_platform", () -> new PlatformItemStone(BlockInit.COBBLESTONE_PLATFORM.get(), new Item.Properties()));
	public static final RegistryObject<Item> STONE_BRICK_PLATFORM = ITEMS.register("stone_brick_platform", () -> new PlatformItemStone(BlockInit.STONE_BRICK_PLATFORM.get(), new Item.Properties()));
	public static final RegistryObject<Item> MOSSY_COBBLESTONE_PLATFORM = ITEMS.register("mossy_cobblestone_platform", () -> new PlatformItemStone(BlockInit.MOSSY_COBBLESTONE_PLATFORM.get(), new Item.Properties()));
	public static final RegistryObject<Item> MOSSY_STONE_BRICK_PLATFORM = ITEMS.register("mossy_stone_brick_platform", () -> new PlatformItemStone(BlockInit.MOSSY_STONE_BRICK_PLATFORM.get(), new Item.Properties()));
	public static final RegistryObject<Item> GRANITE_PLATFORM = ITEMS.register("granite_platform", () -> new PlatformItemStone(BlockInit.GRANITE_PLATFORM.get(), new Item.Properties()));
	public static final RegistryObject<Item> DIORITE_PLATFORM = ITEMS.register("diorite_platform", () -> new PlatformItemStone(BlockInit.DIORITE_PLATFORM.get(), new Item.Properties()));
	public static final RegistryObject<Item> ANDESITE_PLATFORM = ITEMS.register("andesite_platform", () -> new PlatformItemStone(BlockInit.ANDESITE_PLATFORM.get(), new Item.Properties()));
	public static final RegistryObject<Item> COBBLED_DEEPSLATE_PLATFORM = ITEMS.register("cobbled_deepslate_platform", () -> new PlatformItemStone(BlockInit.COBBLED_DEEPSLATE_PLATFORM.get(), new Item.Properties()));
	public static final RegistryObject<Item> DEEPSLATE_BRICK_PLATFORM = ITEMS.register("deepslate_brick_platform", () -> new PlatformItemStone(BlockInit.DEEPSLATE_BRICK_PLATFORM.get(), new Item.Properties()));
	public static final RegistryObject<Item> BRICK_PLATFORM = ITEMS.register("brick_platform", () -> new PlatformItemStone(BlockInit.BRICK_PLATFORM.get(), new Item.Properties()));
	public static final RegistryObject<Item> MUD_BRICK_PLATFORM = ITEMS.register("mud_brick_platform", () -> new PlatformItemStone(BlockInit.MUD_BRICK_PLATFORM.get(), new Item.Properties()));
	public static final RegistryObject<Item> SANDSTONE_PLATFORM = ITEMS.register("sandstone_platform", () -> new PlatformItemStone(BlockInit.SANDSTONE_PLATFORM.get(), new Item.Properties()));
	public static final RegistryObject<Item> RED_SANDSTONE_PLATFORM = ITEMS.register("red_sandstone_platform", () -> new PlatformItemStone(BlockInit.RED_SANDSTONE_PLATFORM.get(), new Item.Properties()));
	public static final RegistryObject<Item> PRISMARINE_PLATFORM = ITEMS.register("prismarine_platform", () -> new PlatformItemStone(BlockInit.PRISMARINE_PLATFORM.get(), new Item.Properties()));
	public static final RegistryObject<Item> NETHER_BRICK_PLATFORM = ITEMS.register("nether_brick_platform", () -> new PlatformItemStone(BlockInit.NETHER_BRICK_PLATFORM.get(), new Item.Properties()));
	public static final RegistryObject<Item> RED_NETHER_BRICK_PLATFORM = ITEMS.register("red_nether_brick_platform", () -> new PlatformItemStone(BlockInit.RED_NETHER_BRICK_PLATFORM.get(), new Item.Properties()));
	public static final RegistryObject<Item> BLACKSTONE_PLATFORM = ITEMS.register("blackstone_platform", () -> new PlatformItemStone(BlockInit.BLACKSTONE_PLATFORM.get(), new Item.Properties()));
	public static final RegistryObject<Item> QUARTZ_PLATFORM = ITEMS.register("quartz_platform", () -> new PlatformItemStone(BlockInit.QUARTZ_PLATFORM.get(), new Item.Properties()));

}
